In [1]:
import numpy as np

# **Soal 1**

In [2]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

B = np.array([[1, 2], 
              [3, 4], 
              [5, 6],
              [7, 8],
              [1, 2],
              [3, 4],
              [5, 6],
              [1, 2]])

C = np.array([[1, 2, 3, 4, 5], 
              [5, 4, 3, 2, 1],
              [1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5],
              [5, 4, 3, 2, 1]])

In [13]:
print(f'matrix A: \n {A}')
print(f'dimensions of A: {np.shape(A)}')
print(f'matrix A: \n {B}')
print(f'dimensions of A: {np.shape(B)}')
print(f'the sum of C matrix diagonal element: {np.sum(np.diag(C))}')
# print(f'the sum of C matrix diagonal element: {np.trace(C)}')

matrix A: 
 [[1 2 3 4]
 [5 6 7 8]]
dimensions of A: (2, 4)
matrix A: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]
 [3 4]
 [5 6]
 [1 2]]
dimensions of A: (8, 2)
the sum of C matrix diagonal element: 13
the sum of C matrix diagonal element: 13


# **Soal 2**

In [14]:
U = np.array([[1, 5, 2, 1],
              [3, 1, 2, -1],
              [5, 1, 2, 8]])

V = np.array([[11, -5, 12, 1],
              [3, 10, 12, -51],
              [5, 1, 21, 81]])

In [15]:
A = (U-V)/2
print(A)

[[ -5.    5.   -5.    0. ]
 [  0.   -4.5  -5.   25. ]
 [  0.    0.   -9.5 -36.5]]


# **Soal 3**

In [23]:
# weight list
w_1_list = [1, 2, 3]
w_2_list = [2, 3, 4]
p_1_list = [1, 2]
p_2_list = [3, 4]
p_3_list = [5, 6]
r_list = [5, 10]

# input
area = 30.0
room = 2

x = np.array([[area], [room]])

In [40]:
W = np.stack((w_1_list, w_2_list))
P = np.stack((p_1_list, p_2_list, p_3_list))
R = np.array(r_list)

W = W.T
P = P.T

HL_1 = W@x
HL_2 = P@HL_1

price = R@HL_2

float(price)

12810.0